# Add application configuration variables here, as shown below.
#
# Usage: (CONFIG loaded from application.rb)
# 
# CONFIG[:aws_access_key]
#

aws_access_key_id: ""
aws_access_key: ""

development:
  aws_s3_bucket_url: ""
  aws_s3_bucket: ""
  
production:
  aws_s3_bucket_url: ""
  aws_s3_bucket: ""